#include "backend/emitters/runtime/runtime.h"

static void emit_runtime_putchar_(backend_t* be)
{
    be_emitf(be,
        "__brl_putchar:\n"
        "    mov  [__brl_ch], dil\n"
        "    mov  rax, 1\n"
        "    mov  rdi, 1\n"
        "    lea  rsi, [__brl_ch]\n"
        "    mov  rdx, 1\n"
        "    syscall\n"
        "    xor  eax, eax\n"
        "    ret\n\n");
}

static void emit_runtime_getchar_(backend_t* be)
{
    be_emitf(be,
        "__brl_getchar:\n"
        "    cmp  byte [__brl_has_unget], 0\n"
        "    je   .L_getchar_read\n"
        "    mov  byte [__brl_has_unget], 0\n"
        "    movzx rax, byte [__brl_unget_ch]\n"
        "    ret\n"
        ".L_getchar_read:\n"
        "    mov  rax, 0\n"
        "    mov  rdi, 0\n"
        "    lea  rsi, [__brl_ch]\n"
        "    mov  rdx, 1\n"
        "    syscall\n"
        "    cmp  rax, 1\n"
        "    jne  .L_getchar_eof\n"
        "    movzx rax, byte [__brl_ch]\n"
        "    ret\n"
        ".L_getchar_eof:\n"
        "    mov  rax, -1\n"
        "    ret\n\n");
}

static void emit_runtime_ungetchar_(backend_t* be)
{
    be_emitf(be,
        "__brl_ungetchar:\n"
        "    cmp  rdi, 0\n"
        "    jl   .L_unget_ret\n"
        "    mov  [__brl_unget_ch], dil\n"
        "    mov  byte [__brl_has_unget], 1\n"
        ".L_unget_ret:\n"
        "    ret\n\n");
}

static void emit_runtime_print_i64_(backend_t* be)
{
    be_emitf(be,
        "__brl_print_i64:\n"
        "    push rbx\n"
        "    push r12\n"
        "    lea  rsi, [__brl_outbuf + 127]\n"
        "    mov  byte [rsi], 10\n"
        "    mov  rax, rdi\n"
        "    xor  r12d, r12d\n"
        "    cmp  rax, 0\n"
        "    jge  .L_pi_abs\n"
        "    mov  r12d, 1\n"
        "    neg  rax\n"
        ".L_pi_abs:\n"
        "    mov  rbx, 10\n"
        "    cmp  rax, 0\n"
        "    jne  .L_pi_loop\n"
        "    dec  rsi\n"
        "    mov  byte [rsi], '0'\n"
        "    jmp  .L_pi_sign\n"
        ".L_pi_loop:\n"
        "    xor  rdx, rdx\n"
        "    div  rbx\n"
        "    add  dl, '0'\n"
        "    dec  rsi\n"
        "    mov  [rsi], dl\n"
        "    test rax, rax\n"
        "    jne  .L_pi_loop\n"
        ".L_pi_sign:\n"
        "    test r12d, r12d\n"
        "    jz   .L_pi_write\n"
        "    dec  rsi\n"
        "    mov  byte [rsi], '-'\n"
        ".L_pi_write:\n"
        "    lea  rdx, [__brl_outbuf + 128]\n"
        "    sub  rdx, rsi\n"
        "    mov  rax, 1\n"
        "    mov  rdi, 1\n"
        "    syscall\n"
        "    pop  r12\n"
        "    pop  rbx\n"
        "    xor  eax, eax\n"
        "    ret\n\n");
}

static void emit_runtime_print_i64_no_nl_(backend_t* be)
{
    be_emitf(be,
        "__brl_print_i64_no_nl:\n"
        "    push rbx\n"
        "    push r12\n"
        "    lea  rsi, [__brl_outbuf + 128]\n"
        "    mov  rax, rdi\n"
        "    xor  r12d, r12d\n"
        "    cmp  rax, 0\n"
        "    jge  .L_pin_abs\n"
        "    mov  r12d, 1\n"
        "    neg  rax\n"
        ".L_pin_abs:\n"
        "    mov  rbx, 10\n"
        "    cmp  rax, 0\n"
        "    jne  .L_pin_loop\n"
        "    dec  rsi\n"
        "    mov  byte [rsi], '0'\n"
        "    jmp  .L_pin_sign\n"
        ".L_pin_loop:\n"
        "    xor  rdx, rdx\n"
        "    div  rbx\n"
        "    add  dl, '0'\n"
        "    dec  rsi\n"
        "    mov  [rsi], dl\n"
        "    test rax, rax\n"
        "    jne  .L_pin_loop\n"
        ".L_pin_sign:\n"
        "    test r12d, r12d\n"
        "    jz   .L_pin_write\n"
        "    dec  rsi\n"
        "    mov  byte [rsi], '-'\n"
        ".L_pin_write:\n"
        "    lea  rdx, [__brl_outbuf + 128]\n"
        "    sub  rdx, rsi\n"
        "    mov  rax, 1\n"
        "    mov  rdi, 1\n"
        "    syscall\n"
        "    pop  r12\n"
        "    pop  rbx\n"
        "    xor  eax, eax\n"
        "    ret\n\n");
}

static void emit_runtime_print_f64_(backend_t* be)
{
    be_emitf(be,
        "__brl_print_f64:\n"
        "    ; fixed 6 digits after dot\n"
        "    push rbx\n"
        "\n"
        "    movq rax, xmm0\n"
        "    test rax, rax\n"
        "    jns  .L_pf_pos\n"
        "    mov  dil, '-'\n"
        "    call __brl_putchar\n"
        "    xorpd xmm0, [__f64_sign_mask]\n"
        "\n"
        ".L_pf_pos:\n"
        "    cvttsd2si rdi, xmm0\n"
        "    cvtsi2sd xmm1, rdi\n"
        "    subsd xmm0, xmm1\n"
        "    movsd [__brl_tmp_f], xmm0\n"
        "    call __brl_print_i64_no_nl\n"
        "\n"
        "    mov  dil, '.'\n"
        "    call __brl_putchar\n"
        "\n"
        "    movsd xmm0, [__brl_tmp_f]\n"
        "    mov  rbx, 6\n"
        "\n"
        ".L_pf_frac:\n"
        "    mulsd xmm0, [__f64_ten]\n"
        "    cvttsd2si r10, xmm0       ; digit = int(frac * 10)\n"
        "    mov  rdi, r10\n"
        "    add  dil, '0'\n"
        "    call __brl_putchar\n"
        "\n"
        "    cvtsi2sd xmm1, r10\n"
        "    subsd xmm0, xmm1\n"
        "    dec  rbx\n"
        "    jne  .L_pf_frac\n"
        "\n"
        "    mov  dil, 10\n"
        "    call __brl_putchar\n"
        "    pop  rbx\n"
        "    xor  eax, eax\n"
        "    ret\n\n");
}

static void emit_runtime_scan_i64_(backend_t* be)
{
    be_emitf(be,
        "__brl_scan_i64:\n"
        "    push rbx\n"
        "    xor  ebx, ebx              ; result\n"
        "    xor  r8d, r8d              ; negative flag\n"
        "\n"
        ".L_si_skip_ws:\n"
        "    call __brl_getchar\n"
        "    cmp  rax, 0\n"
        "    jl   .L_si_zero\n"
        "    cmp  rax, ' '\n"
        "    jle  .L_si_skip_ws\n"
        "    mov  r9, rax               ; current char\n"
        "\n"
        "    cmp  r9, '-'\n"
        "    jne  .L_si_check_plus\n"
        "    mov  r8d, 1\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "    jmp  .L_si_loop\n"
        "\n"
        ".L_si_check_plus:\n"
        "    cmp  r9, '+'\n"
        "    jne  .L_si_loop\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "\n"
        ".L_si_loop:\n"
        "    cmp  r9, '0'\n"
        "    jb   .L_si_done\n"
        "    cmp  r9, '9'\n"
        "    ja   .L_si_done\n"
        "    imul rbx, rbx, 10\n"
        "    mov  r10, r9\n"
        "    sub  r10, '0'\n"
        "    add  rbx, r10\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "    jmp  .L_si_loop\n"
        "\n"
        ".L_si_done:\n"
        "    mov  rdi, r9\n"
        "    call __brl_ungetchar\n"
        "    mov  rax, rbx\n"
        "    test r8d, r8d\n"
        "    jz   .L_si_ret\n"
        "    neg  rax\n"
        "    jmp  .L_si_ret\n"
        "\n"
        ".L_si_zero:\n"
        "    xor  eax, eax\n"
        "\n"
        ".L_si_ret:\n"
        "    pop  rbx\n"
        "    ret\n\n");
}

static void emit_runtime_scan_f64_(backend_t* be)
{
    be_emitf(be,
        "__brl_scan_f64:\n"
        "    ; returns parsed double in xmm0\n"
        "    ; grammar: [spaces] ['+'|'-'] digits? ['.' digits?]\n"
        "    movsd xmm0, [__f64_zero]\n"
        "    xor  r8d, r8d              ; r8d = negative flag\n"
        "\n"
        ".L_sf_skip_ws:\n"
        "    call __brl_getchar\n"
        "    cmp  rax, 0\n"
        "    jl   .L_sf_ret_zero\n"
        "    cmp  rax, ' '\n"
        "    jle  .L_sf_skip_ws\n"
        "    mov  r9, rax               ; r9 = current char\n"
        "\n"
        "    cmp  r9, '-'\n"
        "    jne  .L_sf_check_plus\n"
        "    mov  r8d, 1\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "    jmp  .L_sf_int_loop\n"
        "\n"
        ".L_sf_check_plus:\n"
        "    cmp  r9, '+'\n"
        "    jne  .L_sf_int_loop\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "\n"
        ".L_sf_int_loop:\n"
        "    cmp  r9, '0'\n"
        "    jb   .L_sf_check_dot\n"
        "    cmp  r9, '9'\n"
        "    ja   .L_sf_check_dot\n"
        "\n"
        "    mulsd xmm0, [__f64_ten]\n"
        "    mov  r10, r9\n"
        "    sub  r10, '0'\n"
        "    cvtsi2sd xmm1, r10\n"
        "    addsd xmm0, xmm1\n"
        "\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "    jmp  .L_sf_int_loop\n"
        "\n"
        ".L_sf_check_dot:\n"
        "    cmp  r9, '.'\n"
        "    jne  .L_sf_apply_sign\n"
        "\n"
        "    movsd xmm2, [__f64_ten]     ; denominator = 10.0\n"
        "\n"
        ".L_sf_frac_next:\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "\n"
        ".L_sf_frac_loop:\n"
        "    cmp  r9, '0'\n"
        "    jb   .L_sf_apply_sign\n"
        "    cmp  r9, '9'\n"
        "    ja   .L_sf_apply_sign\n"
        "\n"
        "    mov  r10, r9\n"
        "    sub  r10, '0'\n"
        "    cvtsi2sd xmm1, r10\n"
        "    divsd xmm1, xmm2\n"
        "    addsd xmm0, xmm1\n"
        "    mulsd xmm2, [__f64_ten]\n"
        "\n"
        "    call __brl_getchar\n"
        "    mov  r9, rax\n"
        "    jmp  .L_sf_frac_loop\n"
        "\n"
        ".L_sf_apply_sign:\n"
        "    mov  rdi, r9\n"
        "    call __brl_ungetchar\n"
        "    test r8d, r8d\n"
        "    jz   .L_sf_ret\n"
        "    xorpd xmm0, [__f64_sign_mask]\n"
        "    ret\n"
        ".L_sf_ret_zero:\n"
        "    movsd xmm0, [__f64_zero]\n"
        "    ret\n"
        "\n"
        ".L_sf_ret:\n"
        "    ret\n\n");
}



void nasm_emit_runtime_io(backend_t* be, const nasm_runtime_use_t* rt)
{
    if (!rt)
        return;

    if (rt->putchar_)        emit_runtime_putchar_(be);
    if (rt->getchar_)        emit_runtime_getchar_(be);
    if (rt->ungetchar_)      emit_runtime_ungetchar_(be);
    if (rt->print_i64)       emit_runtime_print_i64_(be);
    if (rt->print_i64_no_nl) emit_runtime_print_i64_no_nl_(be);
    if (rt->print_f64)       emit_runtime_print_f64_(be);
    if (rt->scan_i64)        emit_runtime_scan_i64_(be);
    if (rt->scan_f64)        emit_runtime_scan_f64_(be);
}
